apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receiver-controller
  labels: 
    app: thanos-receiver-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thanos-receiver-controller
  labels:
    app: thanos-receiver-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-receiver-controller
  labels:
    app: thanos-receiver-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-receiver-controller
subjects:
- kind: ServiceAccount
  name: thanos-receiver-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-receiver-controller
  name: thanos-receiver-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receiver-controller   
  template:
    metadata:
      labels:
        app: thanos-receiver-controller 
    spec:
      containers:
      - args:
        - --configmap-name=thanos-receiver-hashring-config
        - --configmap-generated-name=thanos-receiver-hashring-generated-config
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: thanos-receive-controller:latest
        name: thanos-receiver-controller
        ports:
        - containerPort: 8080
          name: http
      serviceAccount: thanos-receiver-controller